import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import '@/styles/style.scss'
import Providers from '@/components/JProvider';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Providers>
            {children}
        </Providers>
      </body>
    </html>
  )
}
